<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Car;
use AppBundle\Entity\Category;
use AppBundle\Entity\Transmision;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTransmision()
    {
        $entityManager=$this->getEntityManager();

        $dql= 'SELECT c, t FROM AppBundle:Car c JOIN c.transmision t';
        $query = $entityManager->createQuery($dql);



        return $query->getResult();

    }

    /**
     * Query to DTO defining search by transmision and category
     * @param $transmision
     * @param $category
     * @return array
     *
     */
    public function findByCategory($transmision, $category)
    {
        $db=$this->getEntityManager()->getConnection();
        $qb=$db->createQueryBuilder();
        $qb->select('c.id')
            ->from('cars', 'c')
            ->where('c.transmision_id=?')
            ->andWhere('c.category_id=?')
            ->setParameter(0,$transmision)
            ->setParameter(1,$category)
            ->orderBy('id','ASC')
            ;
        $result=$qb->execute();
       return $result->fetchAll();



    }




}
