<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Extra;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\Mapping\ClassMetadata;
/**
 * ExtraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtraRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * ExtraRepository constructor.
     * @param EntityManagerInterface $em
     */
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new ClassMetadata(Extra::class));
    }

    public function save(Extra $extra)
    {
        try
        {
            $this->_em->persist($extra);
            $this->_em->flush();

            return $extra->getId();
        }catch (\Exception $exception){
            return false;
        }
    }

    public function update(Extra $extra)
    {
        try
        {
            $this->_em->merge($extra);
            $this->_em->flush();

            return true;
        }catch (\Exception $exception){
            return false;
        }
    }

    public function find($id, $lockMode = null, $lockVersion = null)
    {
        return parent::find($id, $lockMode, $lockVersion);
    }

    public function findAll()
    {
        return parent::findAll();
    }

    public function delete(Extra $extra)
    {
        try{
            $this->_em->remove($extra);
            $this->_em->flush();

            return true;
        }catch (\Exception $exception){

            return false;
        }
    }
}
