<?php

namespace AppBundle\Repository;

use Symfony\Component\HttpFoundation\Request;

/**
 * SelectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SelectRepository extends \Doctrine\ORM\EntityRepository
{




}
