<?php

namespace AppBundle\Repository;

/**
 * TransmisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransmisionRepository extends \Doctrine\ORM\EntityRepository
{
}
